---

- name: Copy the cluster config script
  copy:
    src: add_cluster_node.sh
    dest: /home/ubuntu/add_cluster_node.sh

- name: Execute the cluster config script
  shell: sh /home/ubuntu/add_cluster_node.sh {{ ansible_eth0.ipv4.address }} {{ item }} {{ COUCHDB_PASSWORD }}
  loop: "{{groups['harvesters']}}"

- name: finish clusters
  shell: 'curl -XPOST "http://admin:{{ COUCHDB_PASSWORD }}@{{ ansible_eth0.ipv4.address }}:5984/_cluster_setup" \ --header "Content-Type: application/json" --data "{\"action\": \"finish_cluster\"}"'


# - name: run my script!
#   become: yes
#   shell: python3 get_all_tweets.py
#   args:
#     chdir: /home/ubuntu/deploy/Data/


# - name: Load Data to couchDB
#   shell: 'curl -d @all_tweets.json -H "Content-type: application/json" -X POST http://127.0.0.1:5984/tweets/_bulk_docs'
#   args:
#     chdir: /home/ubuntu/deploy/Data