---

- name: Copy the cluster config script
  copy:
    src: add_cluster_node.sh
    dest: /home/ubuntu/add_cluster_node.sh

- name: Execute the cluster config script
  shell: sh /home/ubuntu/add_cluster_node.sh {{ ansible_eth0.ipv4.address }} {{ item }}
  loop: "{{groups['harvesters']}}"

- name: finish clusters
  shell: 'curl -XPOST "http://admin:admin@{{ ansible_eth0.ipv4.address }}:5984/_cluster_setup" \ --header "Content-Type: application/json" --data "{\"action\": \"finish_cluster\"}"'