---

- name: Copy the cluster config script
  copy:
    src: add_cluster_node.sh
    dest: /home/ubuntu/add_cluster_node.sh

- name: Execute the cluster config script
  shell: sh /home/ubuntu/add_cluster_node.sh {{ ansible_eth0.ipv4.address }} {{ item }}
  loop: "{{groups['harvesters']}}"

- name: finish clusters
  shell: 'curl -XPOST "http://admin:admin@{{ ansible_eth0.ipv4.address }}:5984/_cluster_setup" \ --header "Content-Type: application/json" --data "{\"action\": \"finish_cluster\"}"'


- name: Create APP Directory
  file: path=/home/ubuntu/deploy state=directory

- name: Git Clone webapp
  git: repo=https://kush0609:kush0887@github.com/parth97/Group-38.git dest=/home/ubuntu/deploy update=yes force=yes
  register: git_finished


# - name: run my script!
#   become: yes
#   shell: python3 get_all_tweets.py
#   args:
#     chdir: /home/ubuntu/deploy/Data/


# - name: Load Data to couchDB
#   shell: 'curl -d @all_tweets.json -H "Content-type: application/json" -X POST http://127.0.0.1:5984/tweets/_bulk_docs'
#   args:
#     chdir: /home/ubuntu/deploy/Data